# -*- coding: utf-8 -*-
"""Named Entity Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11u4_8jAhge3Gxgay9w_fg1cj1hwsstoP

## Install Required Libraries
"""

"""## Import Libraries"""

import torch
import gradio as gr
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline
import pandas as pd

"""## Load the Model and Tokenizer

We will use the model name `Babelscape/wikineural-multilingual-ner` to load its Tokenizer and Model from the HuggingFace Hub.
"""

model_name = "Babelscape/wikineural-multilingual-ner"

print("Loading model...")

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

print("Model loaded successfully ✅")

"""## Build the NER Pipeline


"""

device = 0 if torch.cuda.is_available() else -1

ner_pipeline = pipeline(
    "ner",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple",
    device=device
)

print(f"Pipeline ready, running on: {'GPU' if device == 0 else 'CPU'}")

"""## Helper Function to Display Results Neatly

"""

def extract_entities(text):
    """
    Takes a text string, runs it through the NER model,
    and returns a DataFrame with the extracted entities,
    their type, and confidence score.
    """
    results = ner_pipeline(text)

    if not results:
        print("No entities were found in the text.")
        return pd.DataFrame(columns=["Entity", "Type", "Confidence"])

    df = pd.DataFrame([
        {
            "Entity": r["word"],
            "Type": r["entity_group"],
            "Confidence": round(float(r["score"]), 4)
        }
        for r in results
    ])
    return df

"""## Testing the Model on Different Sentences (Multiple Languages)

"""

# English example
text_en = "Elon Musk is the CEO of Tesla and SpaceX, and he was born in South Africa."

print("Text:", text_en)
print()
extract_entities(text_en)

# French example
text_fr = "Emmanuel Macron est le président de la France et il a visité Paris hier."

print("Text:", text_fr)
print()
extract_entities(text_fr)

# Spanish example
text_es = "Lionel Messi juega para el Inter Miami y nació en Rosario, Argentina."

print("Text:", text_es)
print()
extract_entities(text_es)

"""## Testing the Model on Your Own Text

Change the value of the `my_text` variable to any text you'd like to try, then run the cell to see the extracted entities.
"""

my_text = "Write any text you want to test here"

print("Text:", my_text)
print()
extract_entities(my_text)

"""## Visualizing Entities Highlighted Inside the Text

"""

from IPython.display import display, HTML

entity_colors = {
    "PER": "#ffadad",   # Person - pink
    "LOC": "#a0e7e5",   # Location - turquoise
    "ORG": "#ffd6a5",   # Organization - light orange
    "MISC": "#caffbf"   # Miscellaneous - light green
}

def highlight_entities(text):
    """
    Takes a text string and returns/displays the same text
    with the entities detected by the model highlighted,
    each entity type in a different color.
    """
    results = ner_pipeline(text)
    results = sorted(results, key=lambda r: r["start"])

    html_text = ""
    last_idx = 0

    for r in results:
        start, end = r["start"], r["end"]
        entity_type = r["entity_group"]
        color = entity_colors.get(entity_type, "#e0e0e0")

        html_text += text[last_idx:start]
        html_text += (
            f'<span style="background-color:{color}; padding:2px 4px; '
            f'border-radius:4px; margin:0 1px;">'
            f'{text[start:end]} <b style="font-size:10px;">[{entity_type}]</b>'
            f'</span>'
        )
        last_idx = end

    html_text += text[last_idx:]
    display(HTML(f'<div style="font-size:16px; line-height:2;">{html_text}</div>'))

highlight_entities(text_en)

"""## Building an Interactive Gradio Interface

"""

def build_highlighted_html(text):
    """
    A version of the highlighting function that returns an
    HTML string (instead of displaying it directly) so it can
    be rendered inside the Gradio interface.
    """
    if not text or not text.strip():
        return "<p>Please enter some text first.</p>"

    results = ner_pipeline(text)
    results = sorted(results, key=lambda r: r["start"])

    if not results:
        return f'<div style="font-size:16px;">{text}</div><p><i>No entities were found.</i></p>'

    html_text = ""
    last_idx = 0

    for r in results:
        start, end = r["start"], r["end"]
        entity_type = r["entity_group"]
        color = entity_colors.get(entity_type, "#e0e0e0")

        html_text += text[last_idx:start]
        html_text += (
            f'<span style="background-color:{color}; padding:2px 4px; '
            f'border-radius:4px; margin:0 1px;">'
            f'{text[start:end]} <b style="font-size:10px;">[{entity_type}]</b>'
            f'</span>'
        )
        last_idx = end

    html_text += text[last_idx:]
    return f'<div style="font-size:16px; line-height:2;">{html_text}</div>'

def analyze_text(text):
    """
    The main function used by Gradio:
    takes the text and returns (1) highlighted HTML and (2) a DataFrame of entities.
    """
    html_output = build_highlighted_html(text)
    df_output = extract_entities(text) if text and text.strip() else pd.DataFrame(columns=["Entity", "Type", "Confidence"])
    return html_output, df_output

examples = [
    "Elon Musk is the CEO of Tesla and SpaceX, and he was born in South Africa.",
    "Emmanuel Macron est le président de la France et il a visité Paris hier.",
    "Lionel Messi juega para el Inter Miami y nació en Rosario, Argentina."
]

demo = gr.Interface(
    fn=analyze_text,
    inputs=gr.Textbox(
        label="Enter your text",
        placeholder="Type a sentence in any of the 9 supported languages...",
        lines=4
    ),
    outputs=[
        gr.HTML(label="Text with Highlighted Entities"),
        gr.Dataframe(label="Extracted Entity Details", headers=["Entity", "Type", "Confidence"])
    ],
    examples=examples,
    title="Multilingual Named Entity Recognition (WikiNEuRal)",
    description=(
        "An interactive interface for recognizing named entities (persons, locations, "
        "organizations, and more) using the Babelscape/wikineural-multilingual-ner model, "
        "which supports 9 languages: German, English, Spanish, French, Italian, Dutch, "
        "Polish, Portuguese, and Russian."
    )
)

demo.launch(debug=True)